name: Deploy Nodejs to GKE using GitHub

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: github-actions-111
  GKE_ZONE: us-central1
  GKE_CLUSTER: cluster
  REPOSITORY_NAME: my-gke-repo
  FRONTEND_IMAGE: frontend
  BACKEND_IMAGE: backend
  NAMESPACE: default

jobs:
  deploy:
    name: Deploy Nodejs to GKE using GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Cloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Frontend Image
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.FRONTEND_IMAGE }}:latest \
            -f frontend/Dockerfile frontend
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.FRONTEND_IMAGE }}:latest

      - name: Build and Push Backend Image
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.BACKEND_IMAGE }}:latest \
            -f backend/Dockerfile backend
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.BACKEND_IMAGE }}:latest

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Deploy to GKE
        run: kubectl apply -f k8s/
